name: khmer_fonts
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
flutter_gen:
  output: lib/src/ # Optional (default: lib/gen/)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # example:
  fonts:
    - family: Angkor
      fonts:
        - asset: lib/src/fonts/Angkor/Angkor-Regular.ttf
    - family: Moul
      fonts:
        - asset: lib/src/fonts/Moul/Moul-Regular.ttf
    - family: Battambang
      fonts:
        - asset: lib/src/fonts/Battambang/Battambang-Regular.ttf
        - asset: lib/src/fonts/Battambang/Battambang-Bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

